### ISSUE TITLE
Resetting the watch via UC2000Com

### ISSUE THREAD

**Issue by llysdal** [azya52/Seiko#1]
The original keyboard could reset the watch - given that all 4 buttons were pressed on the watch.

I've encountered a few times where the transfer to the watch goes wrong, and it ends up making it unusable until the watch is reset. Would it be possible to implement a way to reset the watch using the UC2000Com program?

**Comment by azya52** [comment]
Sorry, I just saw the message.
If still relevant - to reset, press the STOP button in the app, then all 4 buttons on the watch.
