### ISSUE TITLE
[ 11 ] applications on MacBook Pro for ONLY [ 1 ] Printer !!! WHY? 

### ISSUE THREAD

**Issue by soundofnature** [azya52/Seiko#3]
Dear Epson creators developers, I would love to see an upgrade in installing ONLY one app for all its functions and not like elven apps dispersed on mac systems, not pleasant. Would you mind removing the redundancies that exist? Thank you
<img width="1440" alt="Screenshot 2021-10-13 at 10 33 43" src="https://user-images.githubusercontent.com/5212595/137304023-e127d7e0-47a3-413b-a3ac-a8a15c37d161.png">
.

**Comment by azya52** [comment]
Sorry, you have come to the wrong address - I am not an Epson representative.
