### ISSUE TITLE
Documentation for commands sent to watch

### ISSUE THREAD

**Issue by jockm** [azya52/Seiko#4]
Here is a snippet of code from `uc2000dt.cpp`

```	comPort->writeSerialPort(0x11);
	Sleep(100);
	comPort->writeSerialPort(0x18);
	if (runAferLoad) {
		Sleep(100);
		comPort->writeSerialPort(0x07);
		Sleep(100);
		comPort->writeSerialPort(0x18);
	}
```

I have been trying to find documentation for what these various hex constants (`0x07`, `0x11`, `0x18`, etc) being sent do.  For example if I wanted to write a modern BASIC interpreter and use my UC-2000 as the display, how could I find out the commands to send to do that? 

It's quite possible I have simply missed it, apologies in advance if I have

**Comment by azya52** [comment]
Hello!
Very embarrassing, but I just now saw your message, GitHub for some reason did not send notifications about new issues :(
Regarding your question: if still relevant, then some codes can be found here - https://web.archive.org/web/20201129075800/http://www.sigma957.org/uc_comm.html
